[package]
name = 'day03'
version = '0.0.1'
edition = '2024'

[dependencies]
aoc = {path = "../../aoc"}
parse-display = "0.10.0"
regex = "1.12.2"
rayon = "1.11.0"

[[bin]]
name = 'day03'
path = 'main.rs'
