[package]
name = 'day04'
version = '0.0.1'
edition = '2021'

[dependencies]
aoc = {path = "../../aoc"}
parse-display = "0.10.0"

[dependencies.pancurses]
version = "0.17"
features = ["win32"]

[[bin]]
name = 'day04'
path = 'main.rs'

[features]
vis = []